maxOrganizationCount: 10

server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 9001

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:demo
  properties:
    hibernate.hbm2ddl.auto: create-drop
    hibernate.archive.autodetection: class, hbm
    hibernate.show_sql: true

authentication:
  googleClientId: YOUR_CLIENT_ID_HERE
  jwtSigningSecret: kQCTd0ypLpoFbRt8vTSaHp37kPsKMdh1wzDiuJUa