maxOrganizationCount: 10
serverApplicationHost: http://localhost:8080
guiApplicationHost: http://localhost:8080

server:
  rootPath: /api/
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 9001

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:demo
  properties:
    hibernate.hbm2ddl.auto: create-drop
    hibernate.archive.autodetection: class, hbm
    hibernate.show_sql: true

authentication:
  googleClientId: YOUR_CLIENT_ID_HERE
  googleClientSecret: YOUR_CLIENT_SECRET_HERE
  microsoftClientId: YOUR_CLIENT_ID_HERE
  microsoftClientSecret: YOUR_CLIENT_SECRET_HERE
  jwtSigningSecret: kQCTd0ypLpoFbRt8vTSaHp37kPsKMdh1wzDiuJUa


smtp:
  # Sample configuration in case you want to send your mails using Gmail
  host: smtp.googlemail.com
  port: 465
  username: YOUR_GOOGLE_EMAIL_ADDRESS
  password: YOUR_GOOGLE_PASSWORD
  fromAddress: YOUR_GOOGLE_EMAIL_ADDRESS
  ssl: true
